# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUploadimage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uploadimage(self):
    self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
    self.driver.set_window_size(1222, 1040)
    self.driver.find_element(By.CSS_SELECTOR, "#menu_manageTools > .frame_nav_item_title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".manageTools_cnt_item:nth-child(5) .manageTools_cnt_item_desc_text").click()
    self.driver.find_element(By.LINK_TEXT, "图片").click()
    self.driver.find_element(By.LINK_TEXT, "添加图片").click()
    self.driver.find_element(By.ID, "js_upload_input").click()
    self.driver.find_element(By.LINK_TEXT, "完成").click()
  
