# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestaddmember():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testaddmember(self):
    self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
    self.driver.set_window_size(1222, 823)
    self.driver.find_element(By.CSS_SELECTOR, ".index_service_cnt_itemWrap:nth-child(1) .index_service_cnt_item_title").click()
    self.driver.find_element(By.ID, "username").send_keys("aaa")
    self.driver.find_element(By.ID, "memberAdd_english_name").click()
    self.driver.find_element(By.ID, "memberAdd_acctid").click()
    self.driver.find_element(By.ID, "memberAdd_acctid").send_keys("sssss")
    self.driver.find_element(By.ID, "memberAdd_phone").click()
    self.driver.find_element(By.ID, "memberAdd_phone").send_keys("1232412424")
    self.driver.find_element(By.CSS_SELECTOR, ".ww_commonImg_SmallGrayMore").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ww_commonImg_SmallGrayMore").click()
    self.driver.find_element(By.LINK_TEXT, "修改").click()
    element = self.driver.find_element(By.LINK_TEXT, "修改")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "小闹闹关爱协会").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".js_cancel")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".js_cancel")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".js_cancel")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".js_cancel").click()
    self.driver.find_element(By.CSS_SELECTOR, ".member_edit_joinCheckboxCnt").click()
    self.driver.find_element(By.CSS_SELECTOR, ".member_colRight_operationBar:nth-child(3) > .ww_btn_Blue").click()
    self.driver.find_element(By.CSS_SELECTOR, ".member_colRight_operationBar:nth-child(3) > .ww_btn_Blue").click()
    self.driver.find_element(By.ID, "memberAdd_phone").click()
    self.driver.find_element(By.ID, "memberAdd_phone").click()
    self.driver.find_element(By.ID, "memberAdd_phone").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ww_telInput").click()
    self.driver.find_element(By.ID, "memberAdd_phone").send_keys("15810005017")
    self.driver.find_element(By.CSS_SELECTOR, ".member_colRight_operationBar:nth-child(3) > .ww_btn_Blue").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("bbbb")
    self.driver.find_element(By.ID, "memberAdd_acctid").click()
    self.driver.find_element(By.ID, "memberAdd_acctid").send_keys("ccccccc")
    self.driver.find_element(By.ID, "memberAdd_phone").click()
    self.driver.find_element(By.ID, "memberAdd_phone").send_keys("13522168441")
    self.driver.find_element(By.CSS_SELECTOR, ".js_identity_stat").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".js_identity_stat")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".member_colRight_operationBar:nth-child(3) > .ww_btn_Blue").click()
    self.driver.find_element(By.CSS_SELECTOR, ".member_colRight_operationBar:nth-child(3) > .js_btn_cancel").click()
    self.driver.execute_script("window.scrollTo(0,30)")
  
